use master
GO

IF EXISTS(SELECT * FROM sys.databases WHERE name='BD_WRC')
BEGIN
    DROP DATABASE BD_WRC
END

CREATE DATABASE BD_WRC
GO


USE BD_WRC
GO



EXEC sp_configure filestream_access_level, 2;
RECONFIGURE;

ALTER DATABASE BD_WRC
ADD FILEGROUP FGImages2284873 CONTAINS FILESTREAM;
GO

ALTER DATABASE BD_WRC
ADD FILE (
    NAME = FGImages2284873,
    FILENAME = 'C:\EspaceLabo\FGImages2284873'
)
TO FILEGROUP FGImages2284873;
GO